### ISSUE TITLE
404 Page Creation Required

### ISSUE THREAD

**Issue by Superari15** [yourfirstpr/yourfirstpr.github.io#95] opened 2017-11-12 06:23 UTC
I need a good 404 page for my website - https://github.com/Superari15/funari/issues/1,

**Comment by vattytrivedi** [comment] 2017-11-23 07:47
### Here are few best 404 pages from the [Codepen](https://codepen.io/saransh/pen/aezht).
- https://codepen.io/saransh/pen/aezht 
- https://codepen.io/marcobiedermann/pen/WbGazL?q=+404+page.&limit=all&type=type-pens
- https://codepen.io/kborling/pen/QwbKEe?q=+404+page.&limit=all&type=type-pens
- https://codepen.io/mycnlz/pen/LNbwwj?limit=all&page=2&q=+404+page.
- https://codepen.io/benstanley/pen/JYepog?limit=all&page=2&q=+404+page.

You can find more from the codepen itself

**Comment by pernambucano** [comment] 2017-12-01 02:10
The issue is closed in the original [repo.](https://github.com/Superari15/funari/issues/1) Shouldn't we close this as well?

**Comment by Superari15** [comment] 2017-12-03 10:17
Yes.
On 01-Dec-2017, at 7:41 AM, Paulo Fernandes <notifications@github.com<mailto:notifications@github.com>> wrote:


The issue is closed in the original repo.<https://github.com/Superari15/funari/issues/1> Shouldn't we close this as well?

**Comment by parthpandyappp** [comment] 2019-10-01 13:34
I'll be very glad to contribute here.

**Closed** 2019-10-02 07:57 UTC
